### ISSUE TITLE
Mod Removed

### ISSUE THREAD

**Issue by Zero-Requiem22** [dzfischer/SeedsPleaseMegaPatchProject#1]
Hello! I'm just here to ask as I'm curious, but what happened to the mod on steam?

**Comment by dzfischer** [comment]
> Hello! I'm just here to ask as I'm curious, but what happened to the mod on steam?

Missed the notification for this, sorry. Though uh, I don't think it was ever removed... Maybe you're mixing it up with Shadow's original Megapatch mod, which was removed as a dependency from the base SeedsPlease in favor of this more updated version? Even that one is still accessible, though. Marking this as closed as I can access it via vpn, but do replay if issue persists somehow.
